name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run against Edge
      run: LT_BROWSER="edge" && php .\tests\LambdaTest.php
      
    - name: Run against Chrome
      run: LT_BROWSER="chrome" && php .\tests\LambdaTest.php
      
    - name: Run against Firefox
      run: LT_BROWSER="firefox" && php .\tests\LambdaTest.php
      
      
